"""add_profile_fields_to_user_model

Revision ID: 3baf9765afdd
Revises: ad867dfb5d67
Create Date: 2025-11-15 06:15:36.875247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3baf9765afdd'
down_revision: Union[str, Sequence[str], None] = 'ad867dfb5d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('desired_position', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('desired_industry', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('career_years', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('career_description', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('education', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('major', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('introduction', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('interview_goal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'interview_goal')
    op.drop_column('user', 'introduction')
    op.drop_column('user', 'skills')
    op.drop_column('user', 'major')
    op.drop_column('user', 'education')
    op.drop_column('user', 'career_description')
    op.drop_column('user', 'career_years')
    op.drop_column('user', 'desired_industry')
    op.drop_column('user', 'desired_position')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
