"""Add video_path to Interview table

Revision ID: 6fc2e44ccdd8
Revises: 74d5be1ee5af
Create Date: 2025-11-11 23:08:27.142364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc2e44ccdd8'
down_revision: Union[str, Sequence[str], None] = '74d5be1ee5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('video_path', sa.String(length=255), nullable=True))
    op.alter_column('interview', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('interview', 'resume_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview', 'resume_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('interview', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('interview', 'video_path')
    # ### end Alembic commands ###
