"""Add audio_path to Answer table

Revision ID: 74d5be1ee5af
Revises: d0adeb5b7ea9
Create Date: 2025-11-11 22:29:23.298085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d5be1ee5af'
down_revision: Union[str, Sequence[str], None] = 'd0adeb5b7ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('audio_path', sa.String(length=255), nullable=True))
    op.alter_column('answer', 'question_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'question_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('answer', 'audio_path')
    # ### end Alembic commands ###
