"""Add analysis fields for audio and video

Revision ID: 77c80ee5cb86
Revises: 6fc2e44ccdd8
Create Date: 2025-11-11 23:29:39.331680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c80ee5cb86'
down_revision: Union[str, Sequence[str], None] = '6fc2e44ccdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('speech_rate', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('silence_ratio', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('gaze_stability', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('expression_stability', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('posture_stability', sa.Float(), nullable=True))
    op.alter_column('analysis', 'interview_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('analysis', 'feedback_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'analysis', ['interview_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis', type_='unique')
    op.alter_column('analysis', 'feedback_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('analysis', 'interview_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('analysis', 'posture_stability')
    op.drop_column('analysis', 'expression_stability')
    op.drop_column('analysis', 'gaze_stability')
    op.drop_column('analysis', 'silence_ratio')
    op.drop_column('analysis', 'speech_rate')
    # ### end Alembic commands ###
