"""add_video_analysis_table

Revision ID: ad867dfb5d67
Revises: 77c80ee5cb86
Create Date: 2025-11-14 03:42:35.983864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad867dfb5d67'
down_revision: Union[str, Sequence[str], None] = '77c80ee5cb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_analysis',
    sa.Column('video_analysis_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('gaze_stability', sa.Float(), nullable=True),
    sa.Column('expression_stability', sa.Float(), nullable=True),
    sa.Column('posture_stability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], ),
    sa.PrimaryKeyConstraint('video_analysis_id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_index(op.f('ix_video_analysis_video_analysis_id'), 'video_analysis', ['video_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_analysis_video_analysis_id'), table_name='video_analysis')
    op.drop_table('video_analysis')
    # ### end Alembic commands ###
