"""Re-create initial schema with all models

Revision ID: d0adeb5b7ea9
Revises: 
Create Date: 2025-11-08 23:34:23.328871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd0adeb5b7ea9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passed_resume',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('resume',
    sa.Column('resume_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('resume_file', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('interview',
    sa.Column('interview_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('resume_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('interview_id')
    )
    op.create_table('analysis',
    sa.Column('analysis_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('answer',
    sa.Column('answer_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('analysis')
    op.drop_table('interview')
    op.drop_table('resume')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('passed_resume')
    # ### end Alembic commands ###
