"""Add feedback and questions to resume model

Revision ID: f33951be3c07
Revises: 3baf9765afdd
Create Date: 2025-11-16 21:01:33.108380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33951be3c07'
down_revision: Union[str, Sequence[str], None] = '3baf9765afdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_question',
    sa.Column('question_id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('resume_id', sa.BigInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.resume_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.add_column('resume', sa.Column('corrected_content', sa.Text(), nullable=True))
    op.add_column('resume', sa.Column('ai_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'ai_feedback')
    op.drop_column('resume', 'corrected_content')
    op.drop_table('generated_question')
    # ### end Alembic commands ###
